// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movies.Datalayer.Models;

public partial class Genre
{
    public int GenreId { get; set; }

    public string GenreDescription { get; set; }

    public virtual ICollection<Movie> Movie { get; set; } = new List<Movie>();
}