// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movies.Datalayer.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public DateOnly ReleaseDate { get; set; }

    public string Title { get; set; }

    public string Overview { get; set; }

    public double Popularity { get; set; }

    public short VoteCount { get; set; }

    public double VoteAverage { get; set; }

    public string OriginalLanguage { get; set; }

    public string PosterUrl { get; set; }

    public virtual ICollection<Genre> Genre { get; set; } = new List<Genre>();
}